// This file is auto-generated by backend/scripts/generate_frontend_contract.py.
// Do not edit manually.

export interface AgentDescriptorResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "published_at": string;
  "runtime_artifact"?: RuntimeArtifactMetadata | null;
  "provenance"?: ProvenanceMetadata | null;
}
export interface AgentPublicationResponse {
  "agent_id": string;
  "published": boolean;
}
export type AgentPublishState = "draft" | "published";
export interface AgentValidationIssueResponse {
  "code": string;
  "message": string;
}
export type AgentValidationStatus = "valid" | "invalid";
export type ArtifactFormat = "jsonl" | "parquet";
export interface CandidateRunSummaryResponse {
  "run_id": string;
  "actual"?: string | null;
  "trace_url"?: string | null;
}
export type CompareOutcome = "improved" | "regressed" | "unchanged_pass" | "unchanged_fail" | "candidate_only" | "baseline_only";
export type CurationStatus = "include" | "exclude" | "review";
export interface DatasetCreate {
  "name": string;
  "description"?: string | null;
  "source"?: string | null;
  "version"?: string | null;
  "rows": Array<DatasetSample>;
}
export interface DatasetResponse {
  "name": string;
  "description"?: string | null;
  "source"?: string | null;
  "version"?: string | null;
  "created_at": string;
  "rows": Array<DatasetSample>;
}
export interface DatasetSample {
  "sample_id": string;
  "input": string;
  "expected"?: string | null;
  "tags"?: Array<string>;
  "slice"?: string | null;
  "source"?: string | null;
  "metadata"?: Record<string, unknown> | null;
  "export_eligible"?: boolean | null;
}
export interface DiscoveredAgentResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "publish_state": AgentPublishState;
  "validation_status": AgentValidationStatus;
  "validation_issues": Array<AgentValidationIssueResponse>;
  "published_at"?: string | null;
  "last_validated_at": string;
  "has_unpublished_changes": boolean;
  "runtime_artifact"?: RuntimeArtifactMetadata | null;
  "provenance"?: ProvenanceMetadata | null;
}
export interface EvalCompareResponse {
  "baseline_eval_job_id": string;
  "candidate_eval_job_id": string;
  "dataset": string;
  "distribution": Record<string, number>;
  "samples": Array<EvalCompareSampleResponse>;
}
export interface EvalCompareSampleResponse {
  "dataset_sample_id": string;
  "baseline_judgement"?: SampleJudgement | null;
  "candidate_judgement"?: SampleJudgement | null;
  "compare_outcome": CompareOutcome;
  "error_code"?: string | null;
  "slice"?: string | null;
  "tags": Array<string>;
  "candidate_run_summary"?: CandidateRunSummaryResponse | null;
}
export interface EvalJobCreateRequest {
  "agent_id": string;
  "dataset": string;
  "project": string;
  "tags"?: Array<string>;
  "scoring_mode"?: ScoringMode;
}
export interface EvalJobResponse {
  "eval_job_id": string;
  "agent_id": string;
  "dataset": string;
  "project": string;
  "tags": Array<string>;
  "scoring_mode": ScoringMode;
  "status": EvalJobStatus;
  "sample_count": number;
  "scored_count": number;
  "passed_count": number;
  "failed_count": number;
  "unscored_count": number;
  "runtime_error_count": number;
  "pass_rate": number;
  "failure_distribution": Record<string, number>;
  "observability"?: ObservabilityMetadata | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "created_at": string;
}
export type EvalJobStatus = "queued" | "running" | "completed" | "failed";
export interface EvalSampleDetailResponse {
  "eval_job_id": string;
  "dataset_sample_id": string;
  "run_id": string;
  "input": string;
  "expected"?: string | null;
  "actual"?: string | null;
  "judgement": SampleJudgement;
  "compare_outcome"?: CompareOutcome | null;
  "failure_reason"?: string | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "tags": Array<string>;
  "slice"?: string | null;
  "source"?: string | null;
  "export_eligible"?: boolean | null;
  "curation_status": CurationStatus;
  "curation_note"?: string | null;
  "published_agent_snapshot"?: Record<string, unknown> | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "latency_ms"?: number | null;
  "tool_calls"?: number | null;
  "phoenix_trace_url"?: string | null;
}
export interface EvalSamplePatchRequest {
  "curation_status"?: CurationStatus | null;
  "curation_note"?: string | null;
  "export_eligible"?: boolean | null;
}
export interface ExportCreateRequest {
  "eval_job_id"?: string | null;
  "baseline_eval_job_id"?: string | null;
  "candidate_eval_job_id"?: string | null;
  "dataset_sample_ids"?: Array<string> | null;
  "judgements"?: Array<SampleJudgement> | null;
  "error_codes"?: Array<string> | null;
  "compare_outcomes"?: Array<CompareOutcome> | null;
  "tags"?: Array<string> | null;
  "slices"?: Array<string> | null;
  "curation_statuses"?: Array<CurationStatus> | null;
  "export_eligible"?: boolean | null;
  "format"?: ArtifactFormat;
}
export interface ExportMetadataResponse {
  "export_id": string;
  "format": ArtifactFormat;
  "created_at": string;
  "path": string;
  "size_bytes": number;
  "row_count": number;
  "source_eval_job_id"?: string | null;
  "baseline_eval_job_id"?: string | null;
  "candidate_eval_job_id"?: string | null;
  "filters_summary": Record<string, unknown>;
}
export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}
export interface ObservabilityMetadata {
  "backend": string;
  "trace_id"?: string | null;
  "trace_url"?: string | null;
  "project_url"?: string | null;
}
export interface ProvenanceMetadata {
  "framework"?: string | null;
  "published_agent_snapshot"?: Record<string, unknown> | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "trace_backend"?: string | null;
  "eval_job_id"?: string | null;
  "dataset_sample_id"?: string | null;
}
export interface RuntimeArtifactMetadata {
  "build_status"?: string | null;
  "source_fingerprint"?: string | null;
  "framework"?: string | null;
  "entrypoint"?: string | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
}
export type SampleJudgement = "passed" | "failed" | "unscored" | "runtime_error";
export type ScoringMode = "exact_match" | "contains";
export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
}
