// This file is auto-generated by backend/scripts/generate_frontend_contract.py.
// Do not edit manually.

export type AdapterKind = "openai-agents-sdk" | "langchain" | "mcp";
export interface AgentDescriptorResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "published_at": string;
}
export interface AgentPublicationResponse {
  "agent_id": string;
  "published": boolean;
}
export type AgentPublishState = "draft" | "published";
export interface AgentValidationIssueResponse {
  "code": string;
  "message": string;
}
export type AgentValidationStatus = "valid" | "invalid";
export interface ArtifactExportRequest {
  "run_ids": Array<string>;
  "format"?: ArtifactFormat;
}
export type ArtifactFormat = "jsonl" | "parquet";
export interface ArtifactMetadataResponse {
  "artifact_id": string;
  "format": ArtifactFormat;
  "run_ids": Array<string>;
  "created_at": string;
  "path": string;
  "size_bytes": number;
}
export interface DatasetCreate {
  "name": string;
  "rows": Array<DatasetSample>;
}
export interface DatasetResponse {
  "name": string;
  "rows": Array<DatasetSample>;
}
export interface DatasetSample {
  "sample_id": string;
  "input": string;
  "expected"?: string | null;
  "tags"?: Array<string>;
}
export interface DiscoveredAgentResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "publish_state": AgentPublishState;
  "validation_status": AgentValidationStatus;
  "validation_issues": Array<AgentValidationIssueResponse>;
}
export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}
export interface RunCreateRequest {
  "project": string;
  "dataset"?: string | null;
  "agent_id": string;
  "input_summary": string;
  "prompt": string;
  "tags"?: Array<string>;
  "project_metadata"?: Record<string, unknown>;
}
export interface RunResponse {
  "run_id": string;
  "input_summary": string;
  "status": RunStatus;
  "latency_ms": number;
  "token_cost": number;
  "tool_calls": number;
  "project": string;
  "dataset"?: string | null;
  "agent_id": string;
  "model": string;
  "agent_type": AdapterKind;
  "tags": Array<string>;
  "created_at": string;
  "project_metadata": Record<string, unknown>;
  "artifact_ref"?: string | null;
  "termination_reason"?: string | null;
}
export type RunStatus = "queued" | "running" | "succeeded" | "failed" | "terminated";
export type StepType = "llm" | "tool" | "planner" | "memory";
export interface TerminateRunResponse {
  "run_id": string;
  "terminated": boolean;
  "status": RunStatus;
  "termination_reason"?: string | null;
}
export interface TraceIngestEvent {
  "run_id": string;
  "span_id": string;
  "parent_span_id"?: string | null;
  "step_type"?: StepType;
  "name": string;
  "input": Record<string, unknown>;
  "output"?: Record<string, unknown>;
  "tool_name"?: string | null;
  "latency_ms"?: number;
  "token_usage"?: number;
  "image_digest"?: string | null;
  "prompt_version"?: string | null;
}
export interface TraceSpanResponse {
  "run_id": string;
  "span_id": string;
  "parent_span_id": string | null;
  "step_type": StepType;
  "input": Record<string, unknown>;
  "output": Record<string, unknown>;
  "tool_name"?: string | null;
  "latency_ms": number;
  "token_usage": number;
  "image_digest"?: string | null;
  "prompt_version"?: string | null;
  "received_at": string;
}
export interface TrajectoryStepResponse {
  "id": string;
  "run_id": string;
  "step_type": StepType;
  "parent_step_id"?: string | null;
  "prompt": string;
  "output": string;
  "model"?: string | null;
  "temperature": number;
  "latency_ms": number;
  "token_usage": number;
  "success": boolean;
  "tool_name"?: string | null;
  "started_at": string;
}
export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
}
