// This file is auto-generated by backend/scripts/generate_frontend_contract.py.
// Do not edit manually.

export type AdapterKind = "openai-agents-sdk" | "langchain" | "mcp";
export interface AgentDescriptorResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "published_at": string;
  "runtime_artifact"?: RuntimeArtifactMetadata | null;
  "provenance"?: ProvenanceMetadata | null;
}
export interface AgentPublicationResponse {
  "agent_id": string;
  "published": boolean;
}
export type AgentPublishState = "draft" | "published";
export interface AgentValidationIssueResponse {
  "code": string;
  "message": string;
}
export type AgentValidationStatus = "valid" | "invalid";
export interface ArtifactExportRequest {
  "run_ids": Array<string>;
  "format"?: ArtifactFormat;
}
export type ArtifactFormat = "jsonl" | "parquet";
export interface ArtifactMetadataResponse {
  "artifact_id": string;
  "format": ArtifactFormat;
  "run_ids": Array<string>;
  "created_at": string;
  "path": string;
  "size_bytes": number;
}
export interface DatasetCreate {
  "name": string;
  "rows": Array<DatasetSample>;
}
export interface DatasetResponse {
  "name": string;
  "rows": Array<DatasetSample>;
}
export interface DatasetSample {
  "sample_id": string;
  "input": string;
  "expected"?: string | null;
  "tags"?: Array<string>;
}
export interface DiscoveredAgentResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "publish_state": AgentPublishState;
  "validation_status": AgentValidationStatus;
  "validation_issues": Array<AgentValidationIssueResponse>;
  "published_at"?: string | null;
  "last_validated_at": string;
  "has_unpublished_changes": boolean;
  "runtime_artifact"?: RuntimeArtifactMetadata | null;
  "provenance"?: ProvenanceMetadata | null;
}
export interface EvalJobCreateRequest {
  "agent_id": string;
  "dataset": string;
  "project": string;
  "tags"?: Array<string>;
  "scoring_mode"?: ScoringMode;
}
export interface EvalJobResponse {
  "eval_job_id": string;
  "agent_id": string;
  "dataset": string;
  "project": string;
  "tags": Array<string>;
  "scoring_mode": ScoringMode;
  "status": EvalJobStatus;
  "sample_count": number;
  "scored_count": number;
  "passed_count": number;
  "failed_count": number;
  "unscored_count": number;
  "runtime_error_count": number;
  "pass_rate": number;
  "failure_distribution": Record<string, number>;
  "observability"?: ObservabilityMetadata | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "created_at": string;
}
export type EvalJobStatus = "queued" | "running" | "completed" | "failed";
export interface EvalSampleResultResponse {
  "eval_job_id": string;
  "dataset_sample_id": string;
  "run_id": string;
  "judgement": SampleJudgement;
  "input": string;
  "expected"?: string | null;
  "actual"?: string | null;
  "failure_reason"?: string | null;
  "error_code"?: string | null;
  "trace_url"?: string | null;
  "tags": Array<string>;
}
export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}
export interface ObservabilityMetadata {
  "backend": string;
  "trace_id"?: string | null;
  "trace_url"?: string | null;
  "project_url"?: string | null;
}
export interface ProvenanceMetadata {
  "framework"?: string | null;
  "published_agent_snapshot"?: Record<string, unknown> | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "trace_backend"?: string | null;
  "eval_job_id"?: string | null;
  "dataset_sample_id"?: string | null;
}
export interface RunCreateRequest {
  "project": string;
  "dataset"?: string | null;
  "agent_id": string;
  "input_summary": string;
  "prompt": string;
  "tags"?: Array<string>;
  "project_metadata"?: Record<string, unknown>;
  "eval_job_id"?: string | null;
  "dataset_sample_id"?: string | null;
}
export interface RunResponse {
  "run_id": string;
  "input_summary": string;
  "status": RunStatus;
  "latency_ms": number;
  "token_cost": number;
  "tool_calls": number;
  "project": string;
  "dataset"?: string | null;
  "eval_job_id"?: string | null;
  "dataset_sample_id"?: string | null;
  "agent_id": string;
  "model": string;
  "entrypoint"?: string | null;
  "agent_type": AdapterKind;
  "tags": Array<string>;
  "created_at": string;
  "project_metadata": Record<string, unknown>;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "execution_backend"?: string | null;
  "container_image"?: string | null;
  "provenance"?: ProvenanceMetadata | null;
  "observability"?: ObservabilityMetadata | null;
  "resolved_model"?: string | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "termination_reason"?: string | null;
}
export type RunStatus = "queued" | "running" | "succeeded" | "failed" | "terminated";
export interface RunTraceSpanResponse {
  "run_id": string;
  "span_id": string;
  "parent_span_id": string | null;
  "step_type": StepType;
  "input": Record<string, unknown>;
  "output": Record<string, unknown>;
  "tool_name"?: string | null;
  "latency_ms": number;
  "token_usage": number;
  "image_digest"?: string | null;
  "prompt_version"?: string | null;
  "trace_backend"?: string | null;
  "received_at": string;
}
export interface RuntimeArtifactMetadata {
  "build_status"?: string | null;
  "source_fingerprint"?: string | null;
  "framework"?: string | null;
  "entrypoint"?: string | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
}
export type SampleJudgement = "passed" | "failed" | "unscored" | "runtime_error";
export type ScoringMode = "exact_match" | "contains";
export type StepType = "llm" | "tool" | "planner" | "memory";
export interface TerminateRunResponse {
  "run_id": string;
  "terminated": boolean;
  "status": RunStatus;
  "termination_reason"?: string | null;
}
export interface TraceIngestEvent {
  "run_id": string;
  "span_id": string;
  "parent_span_id"?: string | null;
  "step_type"?: StepType;
  "name": string;
  "input": Record<string, unknown>;
  "output"?: Record<string, unknown>;
  "tool_name"?: string | null;
  "latency_ms"?: number;
  "token_usage"?: number;
  "image_digest"?: string | null;
  "prompt_version"?: string | null;
  "metadata"?: TraceTelemetryMetadata | null;
}
export interface TraceTelemetryMetadata {
  "agent_id"?: string | null;
  "framework"?: string | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "eval_job_id"?: string | null;
  "dataset_sample_id"?: string | null;
  "prompt_version"?: string | null;
  "image_digest"?: string | null;
}
export interface TrajectoryStepResponse {
  "id": string;
  "run_id": string;
  "step_type": StepType;
  "parent_step_id"?: string | null;
  "prompt": string;
  "output": string;
  "model"?: string | null;
  "temperature": number;
  "latency_ms": number;
  "token_usage": number;
  "success": boolean;
  "tool_name"?: string | null;
  "started_at": string;
}
export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
}
