from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = ROOT / "backend"
FRONTEND_CONTRACT_PATH = ROOT / "frontend" / "src" / "shared" / "api" / "contract.ts"
REF_PREFIX = "#/components/schemas/"

if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.main import app


def _ref_name(ref: str) -> str:
    if not ref.startswith(REF_PREFIX):
        raise ValueError(f"unsupported $ref: {ref}")
    return ref[len(REF_PREFIX) :]


def _indent(text: str, spaces: int = 2) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else line for line in text.splitlines())


def _unique(items: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        ordered.append(item)
    return ordered


def _render_object_literal(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = ["{"]
    for name, property_schema in properties.items():
        optional = "?" if name not in required else ""
        property_type = _render_type(property_schema)
        lines.append(f"  {json.dumps(name)}{optional}: {property_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_type(schema: dict[str, Any]) -> str:
    ref = schema.get("$ref")
    if ref:
        return _ref_name(ref)

    enum_values = schema.get("enum")
    if enum_values:
        return " | ".join(json.dumps(value) for value in enum_values)

    any_of = schema.get("anyOf")
    if any_of:
        rendered = _unique([_render_type(item) for item in any_of])
        return " | ".join(rendered)

    all_of = schema.get("allOf")
    if all_of:
        rendered = _unique([_render_type(item) for item in all_of])
        return " & ".join(rendered)

    schema_type = schema.get("type")
    if schema_type == "array":
        items = schema.get("items", {})
        return f"Array<{_render_type(items)}>"

    if schema_type == "object":
        properties = schema.get("properties")
        if properties:
            return _render_object_literal(schema)

        additional_properties = schema.get("additionalProperties", True)
        if additional_properties is False:
            return "Record<string, never>"
        if additional_properties is True:
            return "Record<string, unknown>"
        return f"Record<string, {_render_type(additional_properties)}>"

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"

    return "unknown"


def _render_declaration(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" and schema.get("properties"):
        body = _indent(_render_object_literal(schema), 0)
        return f"export interface {name} {body}"
    return f"export type {name} = {_render_type(schema)};"


def render_contract_source() -> str:
    openapi_schema = app.openapi()
    components = openapi_schema.get("components", {}).get("schemas", {})
    declarations = [
        _render_declaration(name, schema)
        for name, schema in sorted(components.items(), key=lambda item: item[0])
    ]

    return "\n".join(
        [
            "// This file is auto-generated by backend/scripts/generate_frontend_contract.py.",
            "// Do not edit manually.",
            "",
            *declarations,
            "",
        ]
    )


def write_contract() -> None:
    FRONTEND_CONTRACT_PATH.write_text(render_contract_source(), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate frontend API contract types from backend OpenAPI.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated contract differs from the checked-in file.",
    )
    args = parser.parse_args()

    rendered = render_contract_source()
    existing = FRONTEND_CONTRACT_PATH.read_text(encoding="utf-8") if FRONTEND_CONTRACT_PATH.exists() else None

    if args.check:
        if existing != rendered:
            raise SystemExit("frontend API contract is out of date; run backend/scripts/generate_frontend_contract.py")
        return

    FRONTEND_CONTRACT_PATH.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
