// This file is auto-generated by apps/control-plane/scripts/generate_frontend_contract.py.
// Do not edit manually.

export type AdapterKind = "openai-agents-sdk" | "langchain" | "mcp";
export interface AgentDescriptorResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "framework_version": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "capabilities": Array<string>;
  "published_at": string;
  "source_fingerprint": string;
  "execution_reference": ExecutionReference;
  "default_runtime_profile": ExecutorConfig;
  "latest_validation"?: AgentValidationRunReferenceResponse | null;
  "validation_evidence"?: AgentValidationEvidenceSummaryResponse | null;
  "validation_outcome"?: AgentValidationOutcomeSummaryResponse | null;
}
export interface AgentPublicationResponse {
  "agent_id": string;
  "published": boolean;
}
export type AgentPublishState = "draft" | "published";
export interface AgentValidationEvidenceSummaryResponse {
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "trace_url"?: string | null;
  "terminal_summary"?: string | null;
}
export interface AgentValidationIssueResponse {
  "code": string;
  "message": string;
}
export interface AgentValidationOutcomeSummaryResponse {
  "status": string;
  "reason"?: string | null;
}
export interface AgentValidationRunReferenceResponse {
  "run_id": string;
  "status": string;
  "created_at": string;
  "started_at"?: string | null;
  "completed_at"?: string | null;
}
export type AgentValidationStatus = "valid" | "invalid";
export interface ApprovalPolicyCreateRequest {
  "name": string;
  "description"?: string | null;
  "tool_policies"?: Array<ToolPolicyRule>;
}
export interface ApprovalPolicyResponse {
  "approval_policy_id": string;
  "name": string;
  "description"?: string | null;
  "tool_policies": Array<ToolPolicyRule>;
  "created_at": string;
}
export interface ApprovalPolicySnapshot {
  "approval_policy_id"?: string | null;
  "name"?: string | null;
  "tool_policies"?: Array<ToolPolicyRule>;
}
export type ArtifactFormat = "jsonl" | "parquet";
export interface CandidateRunSummaryResponse {
  "run_id": string;
  "actual"?: string | null;
  "trace_url"?: string | null;
}
export type CompareOutcome = "improved" | "regressed" | "unchanged_pass" | "unchanged_fail" | "candidate_only" | "baseline_only";
export type CurationStatus = "include" | "exclude" | "review";
export interface DatasetCreate {
  "name": string;
  "description"?: string | null;
  "source"?: string | null;
  "version"?: string | null;
  "rows": Array<DatasetSample>;
}
export interface DatasetResponse {
  "name": string;
  "description"?: string | null;
  "source"?: string | null;
  "created_at": string;
  "version"?: string | null;
  "row_count"?: number;
  "rows"?: Array<DatasetSample>;
  "current_version_id"?: string | null;
  "versions": Array<DatasetVersionResponse>;
}
export interface DatasetSample {
  "sample_id": string;
  "input": string;
  "expected"?: string | null;
  "tags"?: Array<string>;
  "slice"?: string | null;
  "source"?: string | null;
  "metadata"?: Record<string, unknown> | null;
  "export_eligible"?: boolean | null;
}
export interface DatasetVersionCreate {
  "version"?: string | null;
  "rows": Array<DatasetSample>;
}
export interface DatasetVersionResponse {
  "dataset_version_id": string;
  "dataset_name": string;
  "version"?: string | null;
  "created_at": string;
  "row_count": number;
  "rows": Array<DatasetSample>;
}
export interface DiscoveredAgentResponse {
  "agent_id": string;
  "name": string;
  "description": string;
  "framework": string;
  "framework_version": string;
  "entrypoint": string;
  "default_model": string;
  "tags": Array<string>;
  "capabilities": Array<string>;
  "publish_state": AgentPublishState;
  "validation_status": AgentValidationStatus;
  "validation_issues": Array<AgentValidationIssueResponse>;
  "published_at"?: string | null;
  "last_validated_at": string;
  "has_unpublished_changes": boolean;
  "source_fingerprint": string;
  "execution_reference"?: ExecutionReference | null;
  "default_runtime_profile": ExecutorConfig;
  "latest_validation"?: AgentValidationRunReferenceResponse | null;
  "validation_evidence"?: AgentValidationEvidenceSummaryResponse | null;
  "validation_outcome"?: AgentValidationOutcomeSummaryResponse | null;
}
export interface EvaluatorConfig {
  "scoring_mode"?: ScoringMode;
  "metadata"?: Record<string, unknown>;
}
export interface ExecutionReference {
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
}
export interface ExecutorConfig {
  "backend": string;
  "runner_image"?: string | null;
  "timeout_seconds"?: number;
  "max_steps"?: number;
  "concurrency"?: number;
  "resources"?: ExecutorResources;
  "tracing_backend"?: string;
  "artifact_path"?: string | null;
  "metadata"?: Record<string, unknown>;
}
export interface ExecutorResources {
  "cpu"?: string | null;
  "memory"?: string | null;
}
export interface ExperimentCompareResponse {
  "baseline_experiment_id": string;
  "candidate_experiment_id": string;
  "dataset_version_id": string;
  "distribution": Record<string, number>;
  "samples": Array<ExperimentCompareSampleResponse>;
}
export interface ExperimentCompareSampleResponse {
  "dataset_sample_id": string;
  "baseline_judgement"?: SampleJudgement | null;
  "candidate_judgement"?: SampleJudgement | null;
  "compare_outcome": CompareOutcome;
  "error_code"?: string | null;
  "slice"?: string | null;
  "tags": Array<string>;
  "candidate_run_summary"?: CandidateRunSummaryResponse | null;
}
export interface ExperimentCreateRequest {
  "name": string;
  "spec": ExperimentSpecRequest;
}
export interface ExperimentResponse {
  "experiment_id": string;
  "name": string;
  "dataset_name": string;
  "dataset_version_id": string;
  "published_agent_id": string;
  "status": ExperimentStatus;
  "tags": Array<string>;
  "spec": ExperimentSpec;
  "sample_count": number;
  "completed_count": number;
  "passed_count": number;
  "failed_count": number;
  "unscored_count": number;
  "runtime_error_count": number;
  "pass_rate": number;
  "failure_distribution": Record<string, number>;
  "tracing"?: TracingMetadata | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "created_at": string;
}
export interface ExperimentRunResponse {
  "run_id": string;
  "experiment_id": string;
  "dataset_sample_id": string;
  "input": string;
  "expected"?: string | null;
  "actual"?: string | null;
  "run_status": string;
  "judgement"?: SampleJudgement | null;
  "compare_outcome"?: CompareOutcome | null;
  "failure_reason"?: string | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "tags": Array<string>;
  "slice"?: string | null;
  "source"?: string | null;
  "export_eligible"?: boolean | null;
  "curation_status": CurationStatus;
  "curation_note"?: string | null;
  "published_agent_snapshot"?: Record<string, unknown> | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "executor_backend"?: string | null;
  "latency_ms"?: number | null;
  "tool_calls"?: number | null;
  "trace_url"?: string | null;
}
export interface ExperimentSpec {
  "dataset_version_id": string;
  "published_agent_id": string;
  "model_settings": ModelConfig;
  "prompt_config"?: PromptConfig;
  "toolset_config"?: ToolsetConfig;
  "evaluator_config"?: EvaluatorConfig;
  "executor_config"?: ExecutorConfig | null;
  "approval_policy_id"?: string | null;
  "approval_policy"?: ApprovalPolicySnapshot | null;
  "tags"?: Array<string>;
}
export interface ExperimentSpecRequest {
  "dataset_version_id": string;
  "published_agent_id": string;
  "model_settings": ModelConfig;
  "prompt_config"?: PromptConfig;
  "toolset_config"?: ToolsetConfig;
  "evaluator_config"?: EvaluatorConfig;
  "executor_config"?: ExecutorConfig | null;
  "approval_policy_id"?: string | null;
  "tags"?: Array<string>;
}
export type ExperimentStatus = "draft" | "queued" | "running" | "completed" | "failed" | "cancelled";
export interface ExportCreateRequest {
  "experiment_id"?: string | null;
  "baseline_experiment_id"?: string | null;
  "candidate_experiment_id"?: string | null;
  "dataset_sample_ids"?: Array<string> | null;
  "judgements"?: Array<SampleJudgement> | null;
  "error_codes"?: Array<string> | null;
  "compare_outcomes"?: Array<CompareOutcome> | null;
  "tags"?: Array<string> | null;
  "slices"?: Array<string> | null;
  "curation_statuses"?: Array<CurationStatus> | null;
  "export_eligible"?: boolean | null;
  "format"?: ArtifactFormat;
}
export interface ExportMetadataResponse {
  "export_id": string;
  "format": ArtifactFormat;
  "created_at": string;
  "path": string;
  "size_bytes": number;
  "row_count": number;
  "source_experiment_id"?: string | null;
  "baseline_experiment_id"?: string | null;
  "candidate_experiment_id"?: string | null;
  "filters_summary": Record<string, unknown>;
}
export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}
export interface ModelConfig {
  "model": string;
  "provider"?: string | null;
  "temperature"?: number;
}
export type PolicyEffect = "allow" | "deny";
export interface PromptConfig {
  "prompt_template"?: string | null;
  "system_prompt"?: string | null;
  "prompt_version"?: string | null;
}
export interface ProvenanceMetadata {
  "framework"?: string | null;
  "framework_version"?: string | null;
  "published_agent_snapshot"?: Record<string, unknown> | null;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "runner_backend"?: string | null;
  "executor_backend"?: string | null;
  "trace_backend"?: string | null;
  "experiment_id"?: string | null;
  "dataset_version_id"?: string | null;
  "dataset_sample_id"?: string | null;
  "approval_policy"?: ApprovalPolicySnapshot | null;
  "toolset"?: ToolsetConfig | null;
  "evaluator"?: EvaluatorConfig | null;
  "executor"?: ExecutorConfig | null;
}
export interface RunEvaluationPatchRequest {
  "curation_status"?: CurationStatus | null;
  "curation_note"?: string | null;
  "export_eligible"?: boolean | null;
}
export interface RunLineage {
  "experiment_id"?: string | null;
  "dataset_name"?: string | null;
  "dataset_version_id"?: string | null;
  "dataset_sample_id"?: string | null;
  "export_batch_ids"?: Array<string>;
}
export interface RunResponse {
  "run_id": string;
  "attempt_id": string;
  "experiment_id"?: string | null;
  "dataset_version_id"?: string | null;
  "input_summary": string;
  "status": RunStatus;
  "latency_ms": number;
  "token_cost": number;
  "tool_calls": number;
  "project": string;
  "dataset"?: string | null;
  "dataset_sample_id"?: string | null;
  "agent_id": string;
  "model": string;
  "entrypoint"?: string | null;
  "agent_type": AdapterKind;
  "tags": Array<string>;
  "created_at": string;
  "project_metadata": Record<string, unknown>;
  "artifact_ref"?: string | null;
  "image_ref"?: string | null;
  "executor_backend"?: string | null;
  "executor_submission_id"?: string | null;
  "attempt": number;
  "started_at"?: string | null;
  "completed_at"?: string | null;
  "runner_backend"?: string | null;
  "execution_backend"?: string | null;
  "container_image"?: string | null;
  "provenance"?: ProvenanceMetadata | null;
  "tracing"?: TracingMetadata | null;
  "trace_pointer"?: TracePointer | null;
  "lineage"?: RunLineage | null;
  "resolved_model"?: string | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
  "termination_reason"?: string | null;
  "terminal_reason"?: string | null;
  "last_heartbeat_at"?: string | null;
  "last_progress_at"?: string | null;
  "lease_expires_at"?: string | null;
}
export type RunStatus = "queued" | "starting" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled" | "lost";
export type SampleJudgement = "passed" | "failed" | "unscored" | "runtime_error";
export type ScoringMode = "exact_match" | "contains";
export interface ToolPolicyRule {
  "tool_name": string;
  "effect": PolicyEffect;
  "description"?: string | null;
}
export interface ToolsetConfig {
  "tools"?: Array<string>;
  "metadata"?: Record<string, unknown>;
}
export interface TracePointer {
  "backend": string;
  "trace_id"?: string | null;
  "trace_url"?: string | null;
  "project_url"?: string | null;
}
export interface TracingMetadata {
  "backend": string;
  "trace_id"?: string | null;
  "trace_url"?: string | null;
  "project_url"?: string | null;
}
export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
}
